@startuml TrackDataPlotterTests

package edu.oakland.test.display02 {
    class TrackDataPlotterTests {
        + void plotIsDisplayed()
        + void nullTrackDataNotAllowed()
        + void invalidTrackDataNotAllowed()
    }
}

@enduml
