@startuml GpsSystemTests

package edu.oakland.test.admin {
    class GpsSystemTests {
        + void initDisplayGPSInterfaceNotNull()
        + void initSatelliteNamesNotNull()
        + void initSatelliteNamesNotEmpty()
        + void gpsSystemsConstructedSuccessfully()
        + void useCase1RunSuccessfully()
        + void uC1ScannerNotNull()
        + void useCase2RunSuccessfully()
        + void uC2ScannerNotNull()
        + void incrementalLatAmountNotNull()
        + void incrementLngAmountNotNull()
        + void initLocationDataPointNotNull()
        + void configureSatellitesRunSuccessfully()
        - String generateRandomNames()
        - LocationDataPoint makeRandomLDP()
        - float makeRandomPos()
    }
}

@enduml
