@startuml DisplayGpsManagerImplementationTests

package edu.oakland.test.display01 {
    class DisplayGpsManagerImplementationTests {
        + void receivedGpsSignalStrengths()
        + void ifAcceptableGpsSignalStrengths()
        + void elsePoorGpsSignalStrengths()
        + void middlewareGisIsNotNull()
    }
}

@enduml
