@startuml DisplayCommInterfaceImplementationTests

package edu.oakland.test.display02 {
    class DisplayCommInterfaceImplementationTests {
        + void displayComm2WayIsNotNull()
        + void rfidInIsRfidOut()

    }
}

@enduml
